services:
  discovery-service:
    image: 350801433917.dkr.ecr.eu-west-1.amazonaws.com/products/iop/xvalue/ds:5.1.2
    restart: always
    networks:
      - global_ais
    environment:
        JAVA_OPTS: -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/dumps
    env_file: 
      - path: ./environments/${DS_WORKSPACE}/env/services.env
    user: ${DS_DOCKER_USER}
    logging:
        driver: "json-file"  # Set the logging driver
        options:
            max-size: ${DS_LOGGING_MAX_SIZE}      # Maximum size in megabytes of log file before rotation
            max-file: ${DS_LOGGING_MAX_FILE}        # Maximum number of log files to keep
    deploy:
        resources:
            limits:
                cpus: ${DS_CPU_LIMITS}
                memory: ${DS_MEM_LIMITS}
    volumes:
        - ./environments/${DS_WORKSPACE}/conf/:/tomcat/x1v1/conf/
networks:
  global_ais:
    name: ${DS_NETWORK}
    external: true