services:
  device-manager:
    image: 350801433917.dkr.ecr.eu-west-1.amazonaws.com/products/iop/device-manager-snapshot:compact_3.1.0
    restart: always
    networks:
      - global_ais
    user: ${DEDALUS_DOCKER_USER}
    logging:
        driver: "json-file"  # Set the logging driver
        options:
            max-size: "10m"      # Maximum size in megabytes of log file before rotation
            max-file: "3"        # Maximum number of log files to keep
    deploy:
        resources:
            limits:
                cpus: '0.6'
                memory: '1500M'
    volumes:
        - /opt/dedalus/docker/${AIS_WORKSPACE}/device_manager/conf/device_manager-conf.xml:/opt/app-root/etc/dmserver-setup.xml
networks:
  global_ais:
    name: ${SHARED_AIS_NETWORK}
    external: true