services:
  discovery-service:
    image: 350801433917.dkr.ecr.eu-west-1.amazonaws.com/products/iop/xvalue/ds:5.1.2
    networks:
      global_ais:
        ipv4_address: ${DS_IP}
    ports:
      - "${DS_PORT}:8080"
    environment:
        JAVA_OPTS: -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/dumps
    env_file: 
      - path: ./ds/env/ds.env
    user: ${DEDALUS_DOCKER_USER}
    logging:
        driver: "json-file"  # Set the logging driver
        options:
            max-size: "10m"      # Maximum size in megabytes of log file before rotation
            max-file: "3"        # Maximum number of log files to keep
    deploy:
        resources:
            limits:
                cpus: '0.6'
                memory: '1500M'
    volumes:
        - /opt/dedalus/docker/${AIS_WORKSPACE}/ds/conf/:/tomcat/x1v1/conf/
networks:
  global_ais:
    name: ${SHARED_AIS_NETWORK}
    external: true