services:
  device-manager:
    image: 350801433917.dkr.ecr.eu-west-1.amazonaws.com/products/iop/device-manager-snapshot:compact_3.1.0
    restart: always
    networks:
      - global_ais
    user: ${DEVICEMANAGER_DOCKER_USER}
    logging:
        driver: "json-file"  # Set the logging driver
        options:
            max-size: ${DEVICEMANAGER_LOGGING_MAX_SIZE}      # Maximum size in megabytes of log file before rotation
            max-file: ${DEVICEMANAGER_LOGGING_MAX_FILE}        # Maximum number of log files to keep
    deploy:
        resources:
            limits:
                cpus: ${DEVICEMANAGER_CPU_LIMITS}
                memory: ${DEVICEMANAGER_MEM_LIMITS}
    volumes:
        - ./environments/${DEVICEMANAGER_WORKSPACE}/conf/device_manager-conf.xml:/opt/app-root/etc/dmserver-setup.xml
networks:
  global_ais:
    name: ${DEVICEMANAGER_NETWORK}
    external: true