services:
  haproxy:
    image: haproxy:2.8.15
    restart: always
    env_file:
      - path: ./environments/${HAPROXY_WORKSPACE}/env/services.env
    ports:
      - ${HTTPS_PORT}:${HTTPS_PORT}
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
      - ${HAPROXY_STATS_PORT}:${HAPROXY_STATS_PORT}
      - ${HAPROXY_HEALTH_CHECK_PORT}:${HAPROXY_HEALTH_CHECK_PORT}
      - ${IVAIS_LM_PROCS_PORT}:${IVAIS_LM_PROCS_PORT}
    volumes:
      - ./environments/${HAPROXY_WORKSPACE}/conf:/usr/local/etc/haproxy:ro 
    networks:
      - global_ais
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    user: ${HAPROXY_DOCKER_USER}
    deploy:
        resources:
            limits:
                cpus: ${HAPROXY_CPU_LIMITS}
                memory: ${HAPROXY_MEM_LIMITS}
    logging:
        driver: "json-file"  # Set the logging driver
        options:
          max-size: ${HAPROXY_LOGGING_MAX_SIZE}
          max-file: ${HAPROXY_LOGGING_MAX_FILE}        # Maximum number of log files to keep

networks:
  global_ais:
    name: ${HAPROXY_NETWORK}
    external: true