services:
  grafana:
    image: grafana/grafana:11.2.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "${MONITORING_GRAFANA}:3000"
    volumes:
      # - ./grafana.ini:/etc/grafana/grafana.ini
      - ../conf/grafana/grafana-config.ini:/etc/grafana/grafana.ini
      - /opt/dedalus/docker/${AIS_WORKSPACE}/grafana/data:/var/lib/grafana
      # - grafana-data:/var/lib/grafana
    networks:
      - global_ais
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
      - prometheus

  loki:
    image: grafana/loki:3.2.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - ../conf/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      # - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - /opt/dedalus/docker/${AIS_WORKSPACE}/loki/data:/loki
      # - loki-data:/loki
    networks:
      - global_ais
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:3.2.0
    deploy:
      mode: global  # Run on every node to collect logs
    volumes:
      - ../conf/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      # - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - global_ais
    command: -config.file=/etc/promtail/promtail-config.yaml

  prometheus:
    image: prom/prometheus:v2.54.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - ../conf/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus.yml
      # - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/dedalus/docker/${AIS_WORKSPACE}/prometheus/data:/prometheus
      # - prometheus-data:/prometheus
    networks:
      - global_ais
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    deploy:
      mode: global  # Run on every node to collect metrics
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - global_ais
    privileged: true

networks:
  global_ais:
    name: ${SHARED_AIS_NETWORK}
    external: true

# volumes:
#   grafana-data:
#   loki-data:
#   prometheus-data: